parameters:
  - name: GitHubToken
    type: string
    default: ""
  - name: DevDivToken
    type: string
    default: ""
  - name: DncengToken
    type: string
    default: ""

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: tagInsertedPullRequest
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: runPRTagger
    steps:
      - task: UseDotNet@2
      - script: dotnet tool install Microsoft.RoslynTools --prerelease --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json -g
        displayName: Install Roslyn Insertion Tool
      - script: echo "Hello world"