pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Tag inserted pull request
  pool: ubuntu-latest
  jobs:
  - job: RunPRTagger
    steps:
      - task: UseDotNet@2
      - script: dotnet tool install Microsoft.RoslynTools --prerelease --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json -g
        displayName: Install Roslyn Insertion Tool
      - script: echo "Hello world"