schedules:
- cron: "0 */12 * * *"
  displayName: Roslyn Tagger Tool
  branches:
    include:
    - main
  always: true

variables:
- group: roslyn-perf-bot

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: tagInsertedPullRequest
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: runPRTagger
    steps:
      - task: UseDotNet@2
      - script: dotnet tool install Microsoft.RoslynTools --prerelease --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json -g
        displayName: Install Roslyn Insertion Tool
      - script: roslyn-tools pr-tagger --github-token  $(roslyn-dotnet-bot-issue-w-pat) --devdiv-azdo-token $(roslyn-dn-bot-devdiv-build-r-release-r-code-r)  --dnceng-azdo-token $(roslyn-dn-bot-dnceng-build-r)
        displayName: Run PR Tagger