# Pipeline to create Github merge PRs using the dotnet bot.

variables:
# Variable group for the bot secret.
- group: RoslynMergeBot
- name: isDryRun
  value: $[eq(variables['Build.Reason'], 'PullRequest')]
- name: isAutomated
  value: true

# Make sure the pipeline doesn't build on commits.
trigger: none

# Trigger dryrun on PRs to main.
pr:
- main

schedules:
- cron: "0 */3 * * *"
  displayName: Roslyn Merge Tool
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET'
  inputs:
    version: 9.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    includePreviewVersions: true

- script: dotnet --info; dotnet run -p $(Build.SourcesDirectory)/src/GitHubCreateMergePRs/GitHubCreateMergePRs.csproj --isDryRun=$(isDryRun) --isAutomated=$(isAutomated) --githubToken=$(BotAccount-dotnet-bot-repo-PAT)
  displayName: 'Run GitHub Create Merge PRs'
